/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import javax.swing.JOptionPane;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author yangminghao
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Login(Game game) {
        this.game = game;
        initComponents();
        this.loginJOption.setVisible(false);
    }

    private Login() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordTxt = new javax.swing.JTextField();
        userNameTxt = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        backgrounLabel = new javax.swing.JLabel();
        loginJOption = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 528));
        getContentPane().setLayout(null);

        passwordTxt.setBackground(new java.awt.Color(238, 161, 161));
        passwordTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTxt);
        passwordTxt.setBounds(330, 280, 290, 40);

        userNameTxt.setBackground(new java.awt.Color(238, 161, 161));
        userNameTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(userNameTxt);
        userNameTxt.setBounds(330, 190, 290, 40);

        loginBtn.setBackground(new java.awt.Color(176, 255, 176));
        loginBtn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn);
        loginBtn.setBounds(330, 340, 140, 50);

        returnBtn.setBackground(new java.awt.Color(176, 255, 176));
        returnBtn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnBtn);
        returnBtn.setBounds(330, 410, 140, 50);

        backgrounLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/RegisterAndLogin.jpg"))); // NOI18N
        backgrounLabel.setMaximumSize(new java.awt.Dimension(800, 528));
        backgrounLabel.setMinimumSize(new java.awt.Dimension(800, 528));
        backgrounLabel.setPreferredSize(new java.awt.Dimension(800, 528));
        getContentPane().add(backgrounLabel);
        backgrounLabel.setBounds(0, 0, 800, 528);
        getContentPane().add(loginJOption);
        loginJOption.setBounds(300, 220, 262, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String userName = userNameTxt.getText();
        String passWord = passwordTxt.getText();
        messageTxt = game.login(userName, passWord);
        System.out.println(messageTxt);
        this.loginJOption.showMessageDialog(null, messageTxt, "LOGIN", JOptionPane.INFORMATION_MESSAGE);
        if(messageTxt.startsWith("Successful",0)){
            this.dispose();
            this.game.setCurrentPlayerName(userName);
            KiwiCountUI kiwiCountUI = new KiwiCountUI(game);
            kiwiCountUI.setVisible(true);
        }else{
            userNameTxt.setText("");
            passwordTxt.setText("");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainMenu menu = new MainMenu(game);
        menu.setVisible(true);
    }//GEN-LAST:event_returnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgrounLabel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JOptionPane loginJOption;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JButton returnBtn;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
    public Game game;
    private String messageTxt;
    
}
