/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author yangminghao
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu(Game game) {
        this.game = game;
        initComponents();
    }

    private MainMenu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        instructionBtn = new javax.swing.JButton();
        rankBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 528));
        setMinimumSize(new java.awt.Dimension(800, 528));
        getContentPane().setLayout(null);

        registerBtn.setBackground(new java.awt.Color(176, 255, 176));
        registerBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registerBtn.setText("Regsiter");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(registerBtn);
        registerBtn.setBounds(320, 220, 150, 50);

        loginBtn.setBackground(new java.awt.Color(176, 255, 176));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn);
        loginBtn.setBounds(320, 160, 150, 50);

        exitBtn.setBackground(new java.awt.Color(176, 255, 176));
        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn);
        exitBtn.setBounds(320, 400, 150, 50);

        instructionBtn.setBackground(new java.awt.Color(176, 255, 176));
        instructionBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructionBtn.setText("Instruction");
        instructionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionBtnActionPerformed(evt);
            }
        });
        getContentPane().add(instructionBtn);
        instructionBtn.setBounds(320, 280, 150, 50);

        rankBtn.setBackground(new java.awt.Color(176, 255, 176));
        rankBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rankBtn.setText("Rank");
        rankBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rankBtn);
        rankBtn.setBounds(320, 340, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/gameMenuBackGround.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 528));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 528));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 528));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login(game);
        login.setVisible(true);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Register register = new Register(game);
        register.setVisible(true);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void rankBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Rank rank = new Rank(game);
        rank.setVisible(true);
    }//GEN-LAST:event_rankBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void instructionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        InstructionNew instruction = new InstructionNew(game);
        instruction.setVisible(true);
    }//GEN-LAST:event_instructionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton instructionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton rankBtn;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables
    public Game game;
}
