/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nz.ac.aut.ense701.gui;

import javax.swing.DefaultComboBoxModel;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author Administrator
 */
public class Rank extends javax.swing.JFrame {

    /**
     * Creates new form Rank
     */
    public Rank(Game game) {
        this.game = game;
        game.rankScores();
        initComponents();
    }

    private Rank() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        retunrnBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(799, 528));
        setMinimumSize(new java.awt.Dimension(799, 528));
        setPreferredSize(new java.awt.Dimension(799, 528));
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(149, 255, 149));

        jList1.setBackground(new java.awt.Color(176, 255, 176));
        jList1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jList1.setForeground(new java.awt.Color(153, 0, 51));
        jList1.setModel(new DefaultComboBoxModel(this.game.rankScores().toArray()));
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 170, 570, 250);

        retunrnBtn.setBackground(new java.awt.Color(176, 255, 176));
        retunrnBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        retunrnBtn.setText("Return");
        retunrnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retunrnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(retunrnBtn);
        retunrnBtn.setBounds(320, 430, 140, 40);

        jLabel1.setBackground(new java.awt.Color(176, 255, 176));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/rankBackGround.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 490);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(260, 120, 452, 402);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retunrnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retunrnBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainMenu menu = new MainMenu(game);
        menu.setVisible(true);
    }//GEN-LAST:event_retunrnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton retunrnBtn;
    // End of variables declaration//GEN-END:variables
    public Game game;
}
