/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import javax.swing.JOptionPane;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author yangminghao
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register(Game game) {
        this.game = game;
        initComponents();
        this.registerOptionPanel.setVisible(false);
    }

    private Register() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordTxt = new javax.swing.JTextField();
        userNameTxt = new javax.swing.JTextField();
        returnBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        backGroundLabel = new javax.swing.JLabel();
        registerOptionPanel = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 528));
        getContentPane().setLayout(null);

        passwordTxt.setBackground(new java.awt.Color(238, 161, 161));
        passwordTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTxt);
        passwordTxt.setBounds(330, 280, 290, 40);

        userNameTxt.setBackground(new java.awt.Color(238, 161, 161));
        userNameTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(userNameTxt);
        userNameTxt.setBounds(330, 190, 290, 40);

        returnBtn.setBackground(new java.awt.Color(176, 255, 176));
        returnBtn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnBtn);
        returnBtn.setBounds(340, 420, 140, 50);

        registerBtn.setBackground(new java.awt.Color(176, 255, 176));
        registerBtn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(registerBtn);
        registerBtn.setBounds(340, 350, 140, 50);

        backGroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/RegisterAndLogin.jpg"))); // NOI18N
        backGroundLabel.setMaximumSize(new java.awt.Dimension(800, 528));
        backGroundLabel.setMinimumSize(new java.awt.Dimension(800, 528));
        backGroundLabel.setPreferredSize(new java.awt.Dimension(800, 528));
        getContentPane().add(backGroundLabel);
        backGroundLabel.setBounds(0, 0, 800, 528);
        getContentPane().add(registerOptionPanel);
        registerOptionPanel.setBounds(280, 230, 262, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainMenu menu = new MainMenu(game);
        menu.setVisible(true);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        String userName = userNameTxt.getText();
        String password = passwordTxt.getText();
        if(!"".equals(userName.trim())&&!"".equals(password.trim())){
            this.registerText = game.register(userName, password);
            this.registerOptionPanel.showMessageDialog(null,this.registerText,"REGISTER",JOptionPane.INFORMATION_MESSAGE);
            if(registerText.startsWith("Congratulations",0)){
                this.dispose();
                MainMenu menu = new MainMenu(game);
                menu.setVisible(true);
            }else{
             userNameTxt.setText("");
             passwordTxt.setText("");
            } 
        }else{
             this.registerOptionPanel.showMessageDialog(null,"The user name and password could not be empty!","REGISTER",JOptionPane.INFORMATION_MESSAGE);
             userNameTxt.setText("");
             passwordTxt.setText("");
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGroundLabel;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JButton registerBtn;
    private javax.swing.JOptionPane registerOptionPanel;
    private javax.swing.JButton returnBtn;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
    public Game game;
    private String registerText;
}
